repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-jsonschema
        # match meta.ymls in one of the subdirectories of modules/nf-core
        files: ^modules/nf-core/.*/meta\.yml$
        args: ["--schemafile", "modules/yaml-schema.json"]
      - id: check-jsonschema
        # match meta.ymls in one of the subdirectories of subworkflows/nf-core
        files: ^subworkflows/nf-core/.*/meta\.yml$
        args: ["--schemafile", "subworkflows/yaml-schema.json"]
      - id: check-github-workflows
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 38.130.1
    hooks:
      - id: renovate-config-validator
