---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
# https://www.10xgenomics.com/support/software/xenium-ranger/latest/analysis/running-pipelines/XR-rename
name: "xeniumranger_rename"
description: The xeniumranger rename module allows you to change the sample region_name and cassette_name throughout all the Xenium Onboard Analysis output files that contain this information.
keywords:
  - spatial
  - rename
  - gene labels
  - transcripts
  - xeniumranger
tools:
  - "xeniumranger":
      description: |
        Xenium Ranger is a set of analysis pipelines that process Xenium In Situ Gene Expression data to relabel, resegment, or import new segmentation results from community-developed tools. Xenium Ranger provides flexible off-instrument reanalysis of Xenium In Situ data. Relabel transcripts, resegment cells with the latest 10x segmentation algorithms, or import your own segmentation data to assign transcripts to cells.
      homepage: "https://www.10xgenomics.com/support/software/xenium-ranger/latest"
      documentation: "https://www.10xgenomics.com/support/software/xenium-ranger/latest/getting-started"
      tool_dev_url: "https://www.10xgenomics.com/support/software/xenium-ranger/latest/analysis"
      licence:
        - "10x Genomics EULA"
# https://www.10xgenomics.com/support/software/xenium-ranger/latest/resources/XR-command-line-arguments#rename
input:
  - xenium_bundle:
      type: Path
      description: |
        Path to the xenium output bundle generated by the Xenium Onboard Analysis(XOA) pipeline
  - region_name:
      type: string
      description: |
        New region name
  - cassette_name:
      type: string
      description: New cassette name
# https://www.10xgenomics.com/support/software/xenium-ranger/latest/analysis/running-pipelines/XR-rename#output
output:
  - outs:
      type: file
      description: Files containing the outputs of xenium ranger, see official 10X Genomics documentation for a complete list https://www.10xgenomics.com/support/software/xenium-ranger/latest/analysis/running-pipelines/rename#output
      pattern: "outs/*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@khersameesh24"
maintainers:
  - "@khersameesh24"
